version: '3'

services:
    nginx:
        image: nginx:1.18
        ports:
            - "${NGINX_HOST}:${NGINX_PORT}:80"
        volumes:
            - ./:/app:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        build: docker/php
        volumes:
            - ./:/app:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz.conf:cached
        user: ${DOCKER_UID}
        working_dir: /app