version: '3'

services:
    nginx:
        restart: always

    php:
        restart: always
        volumes:
            - ./docker/php/php-fpm.prod.conf:/usr/local/etc/php-fpm.d/zzz-prod.conf:cached