admin:
    resource: '@CreonitAdminBundle/Controller/'
    type: annotation
    prefix: /admin

api:
    resource: '../src/Controller/Api/'
    type: annotation
    prefix: /api
    defaults: {_api: true}

api.docs:
    resource: "@CreonitRestBundle/Controller/"
    type:     annotation
    prefix:   /openapi

page:
    resource: .
    type: page

app:
    resource: app_routes.yaml
    type: markup