config:
    required: true

database:
    +:
        name: default
        package: src.Model
        namespace: App\Model
        defaultIdMethod: native
        identifierQuoting: true

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk

    test:
        test: text